### ISSUE TITLE
Add bash completions for `git prune`

### ISSUE THREAD

**Issue by johnlinp** [gitgitgadget/git#642]
Currently, typing `git pr<TAB>` won't auto complete to `git prune`. We should add a bash completion script for it.

**Comment by Denton-L** [comment]
This is intentional. `git prune` is considered a "plumbing" command so it shouldn't be exposed to end-users directly. The "porcelain" command is `git gc`.

Taken from the manpages for `git prune`,

```
In most cases, users will not need to call git prune directly, but should instead call git gc, which handles pruning along with many other housekeeping tasks.
```

**Comment by johnlinp** [comment]
Sometimes, when I run `git status`, I would see messages like:
```
warning: There are too many unreachable loose objects; run 'git prune' to remove them.
```

Therefore, I would assume that the command `git prune` is exposed to end-users.

**Comment by Denton-L** [comment]
Interesting... So from what I can tell, that warning comes from `git gc`, introduced in a087cc9819 (git-gc --auto: protect ourselves from accumulated cruft, 2007-09-17). At that time, `git gc --auto` did not prune by default although that has changed from then to now. That raises two questions for me:

1. Why would `git status` emit this message at all? I don't see any codepath where it calls `run_auto_gc()`.

2. Do you have `gc.pruneExpire` set or something? Or do you have a workflow that creates a lot of discarded objects? Otherwise, whenever gc runs, it should automatically prune unless you're using an ancient version of Git.

Anyway, there's probably one actionable change that we should do which is change that message in `builtin/gc.c` to read "run 'git gc --auto'" instead.

**Comment by johnlinp** [comment]
1. Maybe I recalled incorrectly... Perhaps it's from `git push` or `git pull`...
2. I don't have `gc.pruneExpire` set, and I'm not using some ancient version off Git. I don't think I am using some special workflow, either.

I will submit a PR to change the message. Thank you for the detailed analysis.

**Comment by johnlinp** [comment]
With the discussion in #651, I will submit another PR for `git gc --prune=now`.

**Comment by johnlinp** [comment]
As the discussion in #652, I will start working on providing bash completions for `git prune`.

**Comment by johnlinp** [comment]
#667 was merged into master. Closing this issue.
