### ISSUE TITLE
Sparse-checkout: allow 'git rm' to scope to populated files

### ISSUE THREAD

**Issue by derrickstolee** [gitgitgadget/git#786]
Work has already begun to allow `git grep` to scope specifically to the sparse-checkout definition. Perhaps a similar update to `git rm` could help users with sparse-checkout definitions?

This feature request comes second-hand from a user who hit this and was surprised that it did not work as they expected.

**Comment by derrickstolee** [comment]
This feature might be right up @matheustavares alley, if he has time to look into it. ;)

**Comment by matheustavares** [comment]
Hi, @derrickstolee . I had some time in the morning, so I wrote this prototype patch: https://github.com/matheustavares/git/commit/8d23419b90bdf3228a45dbc8725ac06b1f87d7a2

The change is much simpler for `git-rm` since we don't have to deal with arbitrary trees given in the command line, as we did for `git-grep`. One question: should `git rm --cached` also be restricted to the sparsity patterns, by default; or should this option be unaffected by `sparse.restrictCmds`?

**Comment by derrickstolee** [comment]
@matheustavares thanks for jumping on this so quickly! I left a comment on your commit, but everything else looks great to send upstream.

I think leaving `git rm --cached` to be restricted to the sparse-checkout is a good initial approach. I think that users expect them to do the same thing with the only difference being that the working directory is not modified between the two.

**Comment by dscho** [comment]
I _guess_ this is addressed in [`mt/add-rm-in-sparse-checkout`](https://github.com/gitgitgadget/git/compare/master...mt/add-rm-in-sparse-checkout)?

cc: @matheustavares, @derrickstolee

**Comment by derrickstolee** [comment]
Yes, let's close this issue. Thanks.
